In [4]:
import pandas as pd 
iris = pd.read_csv('iris_dataset.csv')
iris.head()

sepal length  sepal width  petal length  petal width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [5]:
print(pd.unique(iris['species']))

[0 1 2]


In [16]:
iris_input = iris[['sepal length','sepal width','petal length','petal width']].to_numpy()

In [17]:
iris_target = iris['species'].to_numpy()

In [18]:
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target = train_test_split(
iris_input,iris_target,random_state=42)


In [19]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)


In [22]:
#로지스틱 이진 분류

a_b_indexes = (train_target==0)|(train_target==1)
train_a_b = train_scaled[a_b_indexes]
target_a_b = train_target[a_b_indexes]

In [23]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_a_b,target_a_b)

LogisticRegression()

In [24]:
print(lr.predict_proba(train_a_b[:5]))

[[0.98638718 0.01361282]
 [0.99584222 0.00415778]
 [0.04291844 0.95708156]
 [0.00889086 0.99110914]
 [0.98672414 0.01327586]]


In [26]:
print(lr.classes_)

[0 1]


In [27]:
print(lr.coef_,lr.intercept_)

[[ 0.9579382  -1.15499708  1.62543353  1.47075842]] [2.44655599]


In [28]:
#메서드는 로지스틱 회귀 모델의 결정 함수를 계산하여 반환합니다.
#즉 값이 음수면 0으로 양수면 1로 예측함
decisions = lr.decision_function(train_a_b[:5])
print(decisions)

[-4.2830373  -5.47860689  3.10458708  4.71380033 -4.30844279]


In [30]:
#시그모이드 함수 계산 
from scipy.special import expit
print(expit(decisions))

[0.01361282 0.00415778 0.95708156 0.99110914 0.01327586]


In [42]:
#로지스틱회귀 다중 분류 
lr = LogisticRegression(C=20,max_iter=1000)
lr.fit(train_scaled,train_target)
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))


0.9821428571428571
1.0


In [50]:
print(lr.predict(test_scaled[:5]))

[1 0 2 1 1]


In [54]:
import numpy as np
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba,decimals=3))

[[0.    0.99  0.01 ]
 [0.995 0.005 0.   ]
 [0.    0.    1.   ]
 [0.    0.955 0.044]
 [0.    0.959 0.041]]


In [55]:
print(lr.classes_)

[0 1 2]


In [56]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision,decimals=2))

[[ -3.83   4.21  -0.38]
 [ 13.07   7.84 -20.92]
 [-18.64   2.58  16.06]
 [ -4.19   3.63   0.56]
 [ -6.52   4.84   1.68]]


In [57]:
from scipy.special import softmax
proba = softmax(decision, axis=1)
print(np.round(proba,decimals=3))

[[0.    0.99  0.01 ]
 [0.995 0.005 0.   ]
 [0.    0.    1.   ]
 [0.    0.955 0.044]
 [0.    0.959 0.041]]
