In [7]:
import pandas as pd

wine = pd.read_csv('wine.csv')
wine.head()


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [6]:
print(pd.unique(wine['target']))

[0 1 2]


In [9]:
wine_input = wine[['alcohol','malic_acid','ash','alcalinity_of_ash','magnesium','total_phenols','flavanoids','nonflavanoid_phenols','proanthocyanins','color_intensity','hue','od280/od315_of_diluted_wines','proline']].to_numpy()
wine_target = wine['target'].to_numpy()

In [10]:
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target = train_test_split(
wine_input,wine_target)

In [11]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)


In [13]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=20,max_iter=1000)
lr.fit(train_scaled,train_target)
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))


1.0
0.9777777777777777


In [14]:
print(lr.predict(test_scaled[:5]))

[1 1 1 0 0]


In [15]:
print(lr.classes_)

[0 1 2]


In [19]:
import numpy as np
decision= lr.decision_function(test_scaled[:5])
print(np.round(decision,decimals=2))

[[ -0.7    9.78  -9.08]
 [ -5.64  17.61 -11.98]
 [ -0.71   8.49  -7.78]
 [  8.81  -1.2   -7.61]
 [ 10.97  -0.3  -10.66]]


In [20]:
from scipy.special import softmax
proba = softmax(decision, axis=1)
print(np.round(proba,decimals=3))

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
